### ISSUE TITLE
about xml2map@^1.0.2

### ISSUE THREAD

**Issue by jeck5895** [macacajs/macaca-coverage#6]

**Comment by afc163** [comment]
Security holding package

This package contained malicious code and was removed from the registry by the npm security team. A placeholder was published to ensure users are not affected in the future.

Please refer to [www.npmjs.com/advisories?search=xml2map](http://www.npmjs.com/advisories?search=xml2map) for more information.

https://www.npmjs.com/package/xml2map?activeTab=readme

**Comment by xudafeng** [comment]
@jeck5895 抱歉，npm 账户被锁了，部分包被删除，还在联系 npm 团队解决。

**Comment by jeck5895** [comment]
Hi @xudafeng thanks for your immediate response, but do we have a temporary solution for this? We're planning to fork the old version and just replace the xml2map with xml2map2 if it will take time for the npm team to fix the issue.


嗨@xudafeng 感謝您的即時回复，但是我們有臨時解決方案嗎？如果 npm 團隊需要時間來解決這個問題，我們計劃分叉舊版本並用 xml2map2 替換 xml2map。

**Comment by xudafeng** [comment]
@jeck5895 请临时使用xml2map2替代，

https://www.npmjs.com/package/xml2map2

**Comment by jeck5895** [comment]
@xudafeng  會做。謝謝!

**Comment by jeck5895** [comment]
@xudafeng 您好，我們在發布解決方案時遇到了問題。您現在有更新依賴項的計劃嗎？

**Comment by soldiersthb** [comment]
你好，macaca-coverage的依赖没有更新

**Comment by xudafeng** [comment]
https://github.com/macacajs/macaca-coverage/pull/7
